<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="hakemusService"
                  targetNamespace="http://hakemus.service.sade.vm.fi"
                  xmlns:tns="http://hakemus.service.sade.vm.fi"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:messages="http://hakemus.service.sade.vm.fi/messages"
        >

    <wsdl:types>
        <xsd:schema targetNamespace="http://hakemus.service.sade.vm.fi">
            <xsd:import namespace="http://hakemus.service.sade.vm.fi/messages" schemaLocation="hakemusService.xsd" />
        </xsd:schema>
    </wsdl:types>
    
    <wsdl:message name="haeHakemukset">
        <wsdl:part name="parameters" element="messages:haeHakemukset" />
    </wsdl:message>
    
    <wsdl:message name="haeHakemuksetVastaus">
        <wsdl:part name="parameters" element="messages:haeHakemuksetVastaus" />
    </wsdl:message>
    
    <wsdl:portType name="HakemusService">
        <wsdl:documentation>Palvelurajapinta, jonka kautta voidaan hakea hakemuksia hakukohteille</wsdl:documentation>
        <wsdl:operation name="haeHakemukset">
            <wsdl:input message="tns:haeHakemukset" />
            <wsdl:output message="tns:haeHakemuksetVastaus" />
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="HakemusServiceSoapBinding" type="tns:HakemusService">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
        <wsdl:operation name="haeHakemukset">
            <soap:operation soapAction="" style="document" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="HakemusService">
        <wsdl:port name="HakemusServicePort" binding="tns:HakemusServiceSoapBinding">
            <soap:address location="http://localhost:8181/cxf/hakemusService" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>