name: build and publish

on:
  workflow_dispatch:
  release:
    types: [ created ]
  push:
    paths-ignore:
      - '**.md'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest 
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'corretto'
          cache: 'maven'

      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Europe/Helsinki"

      - name: Build with Maven
        shell: bash
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          mvn clean install
    
      - uses: actions/cache@v4
        id: restore-build
        with:
          path: target
          key: ${{ github.sha }}


  prepare:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'corretto'
          server-id: github
          cache: 'maven'

      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Europe/Helsinki"

      - uses: actions/cache@v4
        id: restore-build
        with:
          path: target
          key: ${{ github.sha }}

      - name: Publish to Github packages
        continue-on-error: true
        run: mvn --batch-mode deploy -pl fi.vm.sade.haku:haku,hakemus-api,haku-auditlogger -DskipTests -Pghp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}

      - name: Publish to centralized Github packages repository
        continue-on-error: true
        run: mvn --batch-mode deploy -pl fi.vm.sade.haku:haku,hakemus-api,haku-auditlogger -DskipTests -Pghgp
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
      
      - name: Build package
        run: |
          mvn clean verify -B -Dbranch=${{ github.ref_name }} -Drevision=${{ github.sha }} -DbuildNumber=${{ github.run_number }} -Pit -Dit.usePhantomJs=true

      - uses: actions/cache@v4
        id: cache-build
        with:
          path: target
          key: ${{ github.sha }}
  deploy-virkailija:
    uses: Opetushallitus/.github/.github/workflows/push-scan-java-ecr.yml@main
    with:
      application: haku-virkailija
      base-image: baseimage-war-tomcat9-openjdk8:master
      configfolder: src/main/resources/oph-configuration
      jarfile: haku-app.war
      jarfolder: target
    secrets:
      AWS_UTILITY_ROLE_ARN: ${{ secrets.AWS_OPH_UTILITY_ROLE_ARN }}

  deploy-oppija:
    uses: Opetushallitus/.github/.github/workflows/push-scan-java-ecr.yml@main
    with:
      application: haku-oppija
      base-image: baseimage-war-tomcat9-openjdk8:master
      configfolder: src/main/resources/oph-configuration
      jarfile: haku-app.war
      jarfolder: target
    secrets:
      AWS_UTILITY_ROLE_ARN: ${{ secrets.AWS_OPH_UTILITY_ROLE_ARN }}
