name: build and publish

on:
  workflow_dispatch:
  release:
    types: [ created ]
  push:
    paths-ignore:
      - '**.md'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-test-and-deploy-jar:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'corretto'
          cache: 'maven'
          check-latest: 'true'

      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Europe/Helsinki"

      - name: Build with Maven
        shell: bash
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          mvn clean verify -B -Dbranch=${{ github.ref_name }} -Drevision=${{ github.sha }} -DbuildNumber=${{ github.run_number }} -Pit -Dit.usePhantomJs=true

      - name: Publish to Github packages
        if: ${{ github.event_name == 'release' }}
        run: mvn --batch-mode deploy -pl fi.vm.sade.haku:haku,hakemus-api,haku-auditlogger -DskipTests -Pghp -B
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}

      - uses: actions/cache@v4
        id: cache-build
        with:
          path: haku-app/target
          key: ${{ github.sha }}

  deploy-virkailija:
    needs: [build-test-and-deploy-jar]
    uses: Opetushallitus/.github/.github/workflows/push-scan-java-ecr.yml@main
    with:
      application: haku-virkailija
      base-image: baseimage-war-openjdk8:master
      configfolder: src/main/resources/oph-configuration
      jarfile: haku-app.war
      jarfolder: haku-app/target
      type: war
    secrets:
      AWS_UTILITY_ROLE_ARN: ${{ secrets.AWS_OPH_UTILITY_ROLE_ARN }}
